### ISSUE TITLE
API/IIS - SSL Certificate Chain

### ISSUE THREAD

**Issue by Xyaren** [werdes/Gw2_GuildEmblems#1]
Hello,
while trying to implement your emblem API "https://emblem.werdes.net/" for our Riverside TeamSpeak Bot we encountered an issue:

When doing requests to any URL on your domain, python fails with 

> requests.exceptions.SSLError: HTTPSConnectionPool(host='emblem.werdes.net', port=443): Max retries exceeded with url: /emblem/14762DCE-C2A4-E711-80D5-441EA14F1E44/50 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: **unable to get local issuer certificate** (_ssl.c:1123)')))

I identified the problem by checking the domain with "https://www.ssllabs.com/ssltest/analyze.html?d=emblem.werdes.net" 
It states: 

![image](https://user-images.githubusercontent.com/5864045/93910028-d1359b00-fd00-11ea-93cc-a0957086b0a0.png)

The missing certificate is the culprit, as python (and probably many other environments) are not holding all intermediate certificates.

I tried python with my own Let's Encrypt secured domain (which is providing the full certificate chain) and this seems to work.

Thank you!

**Comment by werdes** [comment]
I changed a few certificate conversion options to _hopefully_ include the intermediate certificates. 
Try again please.

**Comment by Xyaren** [comment]
Perfect. Working as expected.
Thank you for the quick fix !
