### ISSUE TITLE
Feature -Not found handling

### ISSUE THREAD

**Issue by Xyaren** [werdes/Gw2_GuildEmblems#2]
Please add a secondary endpoint returning a 404 if the guild emblem is not found instead of returning a fallback image.
It is currently not detectable if a returned emblem is "real" or the fallback icon.

Instead of an endpoint a parameter could be used.

**Comment by werdes** [comment]
That wouldn't fit into the currently used caching scheme, as 404 results will not be cached by neither my caching strategy nor the API caching, which would result in people being able to permanently run the service into the API ratelimit.

Would a Response Header work for you?

**Comment by Xyaren** [comment]
I would consider that as an "ugly" workaround.
Would it be an option to cache at a slightly lower level ?

**Comment by werdes** [comment]
i looked at the caching a little closer, but i'd have to change a whole lot of things to allow it to cache failed responses, so you will unfortunately have to settle with the response header for now. 
Check the response "Emblem-Status" header, it can either be "OK" or "NotFound".
